CEREBRAS_API_KEY = "csk-n34w89yhfypk28259d2hw49y5hk5fkwkvc9xfdrfd2xn24vc"
OPENAI_API_KEY="fd3c1b0eb0cc45fe849794ab175fe2bc"
UPSTAGE_API_KEY="up_6A0mvYq1HHWcuHFgiH6XkqTlx18XD"
CEREBRAS_API_BASE="https://api.cerebras.ai/v1"
OPENAI_API_BASE="https://api.aimlapi.com"
CEREBRAS_MODEL="llama3.1-70b"
OPENAI_MODEL="o1-preview"
